style: fix shellcheck complaints

diff --git a/bs-agent b/bs-agent
--- a/bs-agent
+++ b/bs-agent
@@ -104,7 +104,7 @@ while getopts ":D:H:M:ilursapvh" opt; do
         D)
             day=${OPTARG}
             day_key="<key>Weekday</key><integer>${day}</integer>"
-            if [ ${day} -gt 7 ] || [ ${day} -lt 0 ]
+            if [ "${day}" -gt 7 ] || [ "${day}" -lt 0 ]
             then
                 echo "-D value for day must be 0-7"
                 exit 1
@@ -113,7 +113,7 @@ while getopts ":D:H:M:ilursapvh" opt; do
         H)
             hour=${OPTARG}
             hour_key="<key>Hour</key><integer>${hour}</integer>"
-            if [ ${hour} -gt 23 ] || [ ${hour} -lt 0 ]
+            if [ "${hour}" -gt 23 ] || [ "${hour}" -lt 0 ]
             then
                 echo "-H value for hour must be 0-23"
                 exit 1
@@ -122,7 +122,7 @@ while getopts ":D:H:M:ilursapvh" opt; do
         M)
             minute=${OPTARG}
             minute_key="<key>Minute</key><integer>${minute}</integer>"
-            if [ ${minute} -gt 59 ] || [ ${minute} -lt 0 ]
+            if [ "${minute}" -gt 59 ] || [ "${minute}" -lt 0 ]
             then
                 echo "-M value for minute must be 0-59"
                 exit 1
@@ -150,9 +150,9 @@ while getopts ":D:H:M:ilursapvh" opt; do
             echo ""
             echo "Backup sets installed as agents"
             echo "-------------------------------"
-            for plist in ${HOME}/Library/LaunchAgents/local.$(hostname -s).backup.*
+            for plist in "${HOME}"/Library/LaunchAgents/local."$(hostname -s)".backup.*
             do
-                echo ${plist} | sed -E "s|^.*\/local\.$(hostname -s)\.backup\.(.*)\.plist|\1|"
+                echo "${plist}" | sed -E "s|^.*\/local\.$(hostname -s || true)\.backup\.(.*)\.plist|\1|"
             done
             exit 0
             ;;
@@ -162,6 +162,10 @@ while getopts ":D:H:M:ilursapvh" opt; do
             ;;
         ?)
             echo "Invalid option: -${OPTARG}"
+            exit 1
+            ;;
+        *)
+            echo "getopts error"
             exit 1
             ;;
     esac
@@ -183,11 +187,11 @@ plist_file="${HOME}/Library/LaunchAgents/${agent_name}.plist"
 # check for non-install options first: -l, -u, -r
 # these take precedence over install
 
-if [ ${do_dump} -eq 1 ]
+if [ "${do_dump}" -eq 1 ]
 then
-    if [ -f ${plist_file} ]
+    if [ -f "${plist_file}" ]
     then
-        cat ${plist_file}
+        cat "${plist_file}"
         exit 0
     else
         echo "No agent plist named:"
@@ -196,12 +200,12 @@ then
     fi
 fi
 
-if [ ${do_load} -eq 1 ]
+if [ "${do_load}" -eq 1 ]
 then
     echo "loading launch agent: ${plist_file}"
-    launchctl bootstrap gui/$(id -u) ${plist_file}
+    launchctl bootstrap gui/"$({ id -u || true; })" "${plist_file}"
     ret=$?
-    if [ $ret -ne 0 ]
+    if [ "${ret}" -ne 0 ]
     then
         echo "launchctl returned error code ${ret}"
         echo "maybe it was already loaded? maybe it's not installed?"
@@ -211,12 +215,12 @@ then
     fi
 fi
 
-if [ ${do_unload} -eq 1 ]
+if [ "${do_unload}" -eq 1 ]
 then
     echo "unloading launch agent: ${plist_file}"
-    launchctl bootout gui/$(id -u) ${plist_file}
+    launchctl bootout gui/"$({ id -u || true; })" "${plist_file}"
     ret=$?
-    if [ $ret -ne 0 ]
+    if [ "${ret}" -ne 0 ]
     then
         echo "launchctl returned error code ${ret}"
         echo "maybe it wasn't loaded? maybe it's not installed?"
@@ -226,12 +230,12 @@ then
     fi
 fi
 
-if [ ${do_run} -eq 1 ]
+if [ "${do_run}" -eq 1 ]
 then
     echo "running launch agent: ${agent_name}"
-    launchctl kickstart gui/$(id -u)/${agent_name}
+    launchctl kickstart gui/"$({ id -u || true; })"/"${agent_name}"
     ret=$?
-    if [ $ret -ne 0 ]
+    if [ "${ret}" -ne 0 ]
     then
         echo "launchctl returned error code ${ret}"
         echo "maybe it wasn't loaded? maybe it's not installed?"
@@ -241,7 +245,7 @@ then
     fi
 fi
 
-if [ ${do_status} -eq 1 ]
+if [ "${do_status}" -eq 1 ]
 then
     echo "status of launch agent: ${agent_name}"
     launchctl list | grep "PID\|${agent_name}"
@@ -251,7 +255,7 @@ fi
 # if none of those other options was specified, then generate the plist and
 # write either to the plist file or to the console
 
-if [ ${do_install} -eq 1 ]
+if [ "${do_install}" -eq 1 ]
 then
     plist_out=${plist_file}
     echo "Writing agent plist to ${plist_file}"
@@ -270,7 +274,7 @@ echo "Found borg executable path to be: ${BORGBIN}"
 
 # TODO script path is hardcoded below. allow for configurable scripts location
 
-cat >${plist_out}<<END
+cat >"${plist_out}"<<END
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
diff --git a/bs-backup b/bs-backup
--- a/bs-backup
+++ b/bs-backup
@@ -49,7 +49,7 @@ usage()
 
 info()
 {
-    printf "%s %s\n" "$( date )" "$*" >&2;
+    printf "%s %s\n" "$( date || true )" "$*" >&2;
 }
 
 list()
@@ -60,8 +60,8 @@ list()
     for cfg in bs-set-*
     do
         BACKUP_SET_DESCRIPTION=""
-        . ./$cfg
-        setname=$(echo $cfg | sed -E "s/bs-set-(.*)\.cfg/\1/")
+        . ./"${cfg}"
+        setname=$(echo "${cfg}" | sed -E "s/bs-set-(.*)\.cfg/\1/")
         printf "%-16s %s\n" "${setname}" "${BACKUP_SET_DESCRIPTION}"
     done
     echo ""
@@ -70,7 +70,7 @@ list()
 trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
 
 # switch to script directory
-cd "$(dirname "$0")"
+cd "$(dirname "$0")" || { echo "error cd to script directory"; exit 1; }
 
 # initialize prune and compact defaults
 doprune=1
@@ -78,14 +78,14 @@ docompact=1
 
 # process command line
 # if no options are passed at all, then show help
-if [ $# == 0 ]
+if [ $# = 0 ]
 then
     usage
     exit 0
 fi
 
 # support --help since that is common
-if [ "$1" == "--help" ]
+if [ "$1" = "--help" ]
 then
     usage
     exit 0
@@ -110,7 +110,7 @@ while getopts ":lvhb:t:n:" opt; do
             exit 0
             ;;
         b)
-            if [ "$action" == "test" ]
+            if [ "${action}" = "test" ]
             then
                 info "you cannot request both -b and -t"
                 exit 1
@@ -120,7 +120,7 @@ while getopts ":lvhb:t:n:" opt; do
             info "requested backup of set: ${setname}"
             ;;
         t)
-            if [ "$action" == "backup" ]
+            if [ "${action}" = "backup" ]
             then
                 info "you cannot request both -b and -t"
                 exit 1
@@ -130,11 +130,11 @@ while getopts ":lvhb:t:n:" opt; do
             info "requested dry-run of set: ${setname}"
             ;;
         n)
-            if [ "${OPTARG}" == "prune" ]
+            if [ "${OPTARG}" = "prune" ]
             then
                 doprune=0
                 info "requested skip pruning"
-            elif [ "${OPTARG}" == "compact" ]
+            elif [ "${OPTARG}" = "compact" ]
             then
                 docompact=0
                 info "requested skip compacting"
@@ -148,21 +148,25 @@ while getopts ":lvhb:t:n:" opt; do
             echo "Invalid option: -${OPTARG}"
             exit 1
             ;;
+        *)
+            echo "getopts error"
+            exit 1
+            ;;
     esac
 done
 
 # determine command action
 # --stats and --dry-run are not compatible switches for borg
-if [ "$action" == "backup" ]
+if [ "${action}" = "backup" ]
 then
     action_switch="--stats"
     filter="--filter AME"
-elif [ "$action" == "test" ]
+elif [ "${action}" = "test" ]
 then
     action_switch="--dry-run"
     filter=""
 else
-    info "bad command: $action"
+    info "bad command: ${action}"
     usage
     exit 1
 fi
@@ -186,7 +190,7 @@ else
     BORG=${BORGBIN}
 fi
 
-if ! command -v ${BORG} 2>&1 >/dev/null
+if ! command -v "${BORG}" >/dev/null 2>&1
 then
     info "could not find borg executable using: ${BORG}"
     exit 1
@@ -236,10 +240,25 @@ else
     exit 1
 fi
 
-info "BACKUP_CUSTOM_FLAGS ..."
-info ${BACKUP_CUSTOM_FLAGS}
-info "BACKUP_SOURCE_PATHS ..."
-info ${BACKUP_SOURCE_PATHS}
+if [ -n "${BACKUP_CUSTOM_FLAGS}" ]
+then
+    info "BACKUP_CUSTOM_FLAGS ..."
+    info "${BACKUP_CUSTOM_FLAGS}"
+else
+    echo "BACKUP_CUSTOM_FLAGS is not defined."
+    echo "Something went wrong with the backup set config file."
+    exit 1
+fi
+
+if [ -n "${BACKUP_SOURCE_PATHS}" ]
+then
+    info "BACKUP_SOURCE_PATHS ..."
+    info "${BACKUP_SOURCE_PATHS}"
+else
+    echo "BACKUP_SOURCE_PATHS is not defined."
+    echo "Something went wrong with the backup set config file."
+    exit 1
+fi
 
 # validate and source the repo credentials
 if [ -f "${repo_config_file}" ]
@@ -250,8 +269,16 @@ else
     exit 1
 fi
 
-info "BORG_REPO ..."
-info "${BORG_REPO}"
+if [ -n "${BORG_REPO}" ]
+then
+    info "BORG_REPO ..."
+    info "${BORG_REPO}"
+else
+    echo "BORG_REPO is not defined."
+    echo "Something went wrong with the configuration file load."
+    exit 1
+fi
+
 info "BORG_PASS... is not shown for security"
 
 # to get quoting, and paths with spaces being included from the 'set' files,
@@ -268,16 +295,16 @@ ${BACKUP_CUSTOM_FLAGS} ::{hostname}-${setname}-{now} ${BACKUP_SOURCE_PATHS}"
 
 # show what will be called
 info "BORG_CLI_ARGS:"
-info $BORG_CLI_ARGS
+info "${BORG_CLI_ARGS}"
 
 info "+++BACKUP: ${setname}"
 # use xargs to expand args and pass to borg. this seems to work
-echo $BORG_CLI_ARGS | xargs ${BORG}
+echo "${BORG_CLI_ARGS}" | xargs "${BORG}"
 
 info "---BACKUP"
 
 # if it was a test run, just exit here
-if [ "$action" == "test" ]
+if [ "${action}" = "test" ]
 then
     info "End of test run"
     exit 0
@@ -285,7 +312,7 @@ fi
 
 backup_exit=$?
 
-if [ $doprune == 1 ]
+if [ "${doprune}" = 1 ]
 then
     info "+++PRUNE"
 
@@ -300,7 +327,7 @@ else
     prune_exit=0
 fi
 
-if [ $docompact == 1 ]
+if [ "${docompact}" = 1 ]
 then
     info "+++COMPACTING"
 
@@ -315,12 +342,12 @@ fi
 global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
 global_exit=$(( compact_exit > global_exit ? compact_exit : global_exit ))
 
-if [ ${global_exit} -eq 0 ]; then
+if [ "${global_exit}" -eq 0 ]; then
     info "Backup, Prune, and Compact finished successfully"
-elif [ ${global_exit} -eq 1 ]; then
+elif [ "${global_exit}" -eq 1 ]; then
     info "Backup, Prune, and/or Compact finished with warnings"
 else
     info "Backup, Prune, and/or Compact finished with errors"
 fi
 
-exit ${global_exit}
+exit "${global_exit}"
diff --git a/bs-install b/bs-install
--- a/bs-install
+++ b/bs-install
@@ -98,14 +98,14 @@ USAGE
 # $2 - destination - where to copy the scripts
 install_bs()
 {
-    local source dest
+    local srcdir dest
 
-    source="$1"
+    srcdir="$1"
     dest="$2"
 
     # save our current location
     cwd=$(pwd)
-    cd "${srcdir}"
+    cd "${srcdir}" || { echo "Could not cd to '${srcdir}'"; exit 1; }
 
     # check to see if any of the scripts already exist at dest
     for script in ${scripts_list}; do
@@ -127,7 +127,7 @@ install_bs()
     # copy the scripts
     for script in ${scripts_list}; do
         echo "copying: ${script}"
-        cp ${script} "${dest}/." || { echo "error copying '${script}'"; exit 1; }
+        cp "${script}" "${dest}/." || { echo "error copying '${script}'"; exit 1; }
     done
 
     # print out aliases
@@ -140,7 +140,7 @@ install_bs()
     echo ""
 
     # go back to original cwd
-    cd ${cwd}
+    cd "${cwd}" || { echo "Could not cd back to cwd: ${cwd}"; exit 1; }
 }
 
 # deletes scripts from the specified source
@@ -212,6 +212,10 @@ while getopts ":hHVs:d:r:m" opt; do
             echo "Invalid option: -${OPTARG}"
             exit 1
             ;;
+        *)
+            echo "getopts error"
+            exit 1
+            ;;
     esac
 done
 
@@ -227,7 +231,7 @@ then
         # user is also requesting man pages installed
         if [ "${man}" = "1" ]
         then
-            cd man
+            cd man || { echo "Could not cd to 'man' directory"; exit 1; }
             ./bs-install-man -i
         fi
     else
@@ -241,7 +245,7 @@ then
     # user is also requesting man pages installed
     if [ "${man}" = "1" ]
     then
-        cd man
+        cd man || { echo "Could not cd to 'man' directory"; exit 1; }
         ./bs-install-man -i
     fi
 else
diff --git a/bs-install-borg b/bs-install-borg
--- a/bs-install-borg
+++ b/bs-install-borg
@@ -95,7 +95,7 @@ USAGE
 
 INSTALL_PATH=/usr/local/share
 EXE_SYMLINK=/usr/local/bin/borg
-PLATFORM="$(uname -s)-$(uname -m)"
+PLATFORM="$(uname -s || true)-$(uname -m || true)"
 
 # clone the board repo
 # checkout version 1.4.0
@@ -114,7 +114,7 @@ make_package()
     pip install -e .
     # add pyinstaller and build package
     pip install pyinstaller
-    pyinstaller -D -n borg-${PLATFORM} src/borg/__main__.py
+    pyinstaller -D -n "borg-${PLATFORM}" src/borg/__main__.py
     deactivate
     cd ..
 }
@@ -159,10 +159,10 @@ fi
 # test option
 if [ "$1" = "-t" ]
 then
-    borg/dist/borg-${PLATFORM}/borg-${PLATFORM} --help
+    "borg/dist/borg-${PLATFORM}/borg-${PLATFORM}" --help
     echo ""
-    borg/dist/borg-${PLATFORM}/borg-${PLATFORM} --version
-    echo "\nIf you see the borg help and the version above, then it's working.\n"
+    "borg/dist/borg-${PLATFORM}/borg-${PLATFORM}" --version
+    printf "\nIf you see the borg help and the version above, then it's working.\n\n"
     exit 0
 fi
 
@@ -196,10 +196,10 @@ then
         echo ""
         exit 1
     fi
-    cp -R borg/dist/borg-${PLATFORM} /usr/local/share/borg-${PLATFORM} ||
-        { echo "Error installing: /usr/local/share/borg-${PLATFORM}\nDo you need sudo?"; exit 1; }
-    ln -s /usr/local/share/borg-${PLATFORM}/borg-${PLATFORM} ${EXE_SYMLINK} ||
-        { echo "Error creating symlink: ${EXE_SYMLINK}\nDo you need sudo?"; exit 1; }
+    cp -R "borg/dist/borg-${PLATFORM}" "/usr/local/share/borg-${PLATFORM}" ||
+        { printf "Error installing: /usr/local/share/borg-%s\nDo you need sudo?\n" "${PLATFORM}"; exit 1; }
+    ln -s "/usr/local/share/borg-${PLATFORM}/borg-${PLATFORM}" "${EXE_SYMLINK}" ||
+        { printf "Error creating symlink: %s\nDo you need sudo?\n" "${EXE_SYMLINK}" ; exit 1; }
     echo ""
     echo "If /usr/local/bin is on your path, you should now be able to type"
     echo "    borg --help"
@@ -213,9 +213,9 @@ if [ "$1" = "-r" ]
 then
     echo ""
     echo "Attempting to remove: ${EXE_SYMLINK}"
-    rm -f ${EXE_SYMLINK} || { echo "Some error occurred. Do you need sudo?"; exit 1; }
+    rm -f "${EXE_SYMLINK}" || { echo "Some error occurred. Do you need sudo?"; exit 1; }
     echo "Attempting to remove: /usr/local/share/borg-${PLATFORM}"
-    rm -rf /usr/local/share/borg-${PLATFORM} ||
+    rm -rf /usr/local/share/borg-"${PLATFORM}" ||
         { echo "Some error occurred. Do you need sudo?"; exit 1; }
     exit 0
 fi
diff --git a/bs-logs b/bs-logs
--- a/bs-logs
+++ b/bs-logs
@@ -68,56 +68,60 @@ USAGE
 list_backups()
 {
     local set_id=1
-    while read logline
+    while read -r logline
     do
         case "${logline}" in
             *+++BACKUP*)
                 echo "${set_id}: ${logline}"
-                set_id=$((${set_id} + 1))
+                set_id=$((set_id + 1))
+                ;;
+            *)
                 ;;
         esac
-    done < ${LOG_PATH}/${LOG_FILE}
+    done < "${LOG_PATH}/${LOG_FILE}"
 }
 
 # copy log to tmp file, except lines which match requested backup number
 # after tmp file is finished, copy back to main log file
 delete_backup()
 {
-    local requested_set=$1
+    local requested_set="$1"
     local set_id=0
     echo "DELETE: ${requested_set}"
 
-    while read logline
+    while read -r logline
     do
         case "${logline}" in
             *+++BACKUP*)
                 # count backup sets while scanning through log file
-                set_id=$((${set_id} + 1))
-                if [ ${set_id} -eq ${requested_set} ]
+                set_id=$((set_id + 1))
+                if [ "${set_id}" -eq "${requested_set}" ]
                 then
                     echo "Deleting: ${logline}"
                 else
                     echo "Keeping:  ${logline}"
                 fi
                 ;;
+            *)
+                ;;
         esac
         # if the current set does not match the requested the copy it out
         # (keep the wanted sets)
         # if this is the requested set then nothing is copied,
         # so those line are "deleted"
-        if [ ${set_id} -ne ${requested_set} ]
+        if [ "${set_id}" -ne "${requested_set}" ]
         then
-            echo ${logline} >> ${TMPFILE}
+            echo "${logline}" >> "${TMPFILE}"
         fi
-    done < ${LOG_PATH}/${LOG_FILE}
-    cp ${TMPFILE} ${LOG_PATH}/${LOG_FILE}
-    rm ${TMPFILE}
+    done < "${LOG_PATH}/${LOG_FILE}"
+    cp "${TMPFILE}" "${LOG_PATH}/${LOG_FILE}"
+    rm "${TMPFILE}"
 }
 
 # make a "backup" copy of the backup log
 save_log()
 {
-    cp ${LOG_PATH}/${LOG_FILE} ${LOG_PATH}/${LOG_FILE}.0
+    cp "${LOG_PATH}/${LOG_FILE}" "${LOG_PATH}/${LOG_FILE}.0"
 }
 
 # remove all but the last N backups from the log
@@ -126,23 +130,25 @@ prune_backup()
     local set_id=$((0 - $1))
 
     # count number of backup sets in the log
-    while read logline
+    while read -r logline
     do
         case "${logline}" in
             *+++BACKUP*)
-                set_id=$((${set_id} + 1))
+                set_id=$((set_id + 1))
+                ;;
+            *)
                 ;;
         esac
-    done < ${LOG_PATH}/${LOG_FILE}
+    done < "${LOG_PATH}/${LOG_FILE}"
     # set_id has the number of backups that need to be deleted
     # delete 0 first to get rid of any leading cruft
     delete_backup 0
     # delete first backup for as many as needed
     # this is inefficent and should be improved, but works
-    while [ ${set_id} -gt 0 ]
+    while [ "${set_id}" -gt 0 ]
     do
         delete_backup 1
-        set_id=$((${set_id} - 1))
+        set_id=$((set_id - 1))
     done
 }
 
@@ -155,8 +161,8 @@ prune_backup()
 # * s - print just a summary of the backup set
 extract_backup()
 {
-    local requested_set=$1
-    local filter=$2
+    local requested_set="$1"
+    local filter="$2"
     local set_id=1
     local extracting=0
     local summarize=0
@@ -167,32 +173,35 @@ extract_backup()
     # IFS is used here to preserve the spacing in the summary table at the
     # end of the borg log
     IFS=''
-    while read logline
+    while read -r logline
     do
         # looking for the backup set to extract
-        if [ ${extracting} -eq 0 ]
+        if [ "${extracting}" -eq 0 ]
         then
             case "${logline}" in
                 *+++BACKUP*)
-                    if [ ${set_id} -eq ${requested_set} ]
+                    if [ "${set_id}" -eq "${requested_set}" ]
                     then
                         extracting=1
-                        echo ${logline}
+                        echo "${logline}"
                     else
-                        set_id=$((${set_id} + 1))
+                        set_id=$((set_id + 1))
                     fi
+                    ;;
+                *)
+                    ;;
             esac
         # backup set is found so extract data from the log file
         else
             case "${logline}" in
                 *+++BACKUP*)
                     echo "Unexpected end of backup set log data"
-                    echo ${logline}
+                    echo "${logline}"
                     return 0
                     ;;
                 *---COMPACTING*)
                     # catch the end of the backup we are extracting
-                    echo ${logline}
+                    echo "${logline}"
                     # if filter "s" print summary counts of each kind of file
                     if [ "${filter}" = "s" ]
                     then
@@ -207,26 +216,26 @@ extract_backup()
                     ;;
                 A\ /*)
                     # sum added files, and print if filter "a" or no filter
-                    countA=$((${countA} + 1))
+                    countA=$((countA + 1))
                     if [ "${filter}" = "a" ] || [ "${filter}" = "" ]
                     then
-                        echo ${logline}
+                        echo "${logline}"
                     fi
                     ;;
                 E\ /*)
                     # sum error files, and print if filter "e" or no filter
-                    countE=$((${countE} + 1))
+                    countE=$((countE + 1))
                     if [ "${filter}" = "e" ] || [ "${filter}" = "" ]
                     then
-                        echo ${logline}
+                        echo "${logline}"
                     fi
                     ;;
                 M\ /*)
                     # sum modified files, and print if filter "m" or no filter
-                    countM=$((${countM} + 1))
+                    countM=$((countM + 1))
                     if [ "${filter}" = "m" ] || [ "${filter}" = "" ]
                     then
-                        echo ${logline}
+                        echo "${logline}"
                     fi
                     ;;
                 --------*)
@@ -237,25 +246,25 @@ extract_backup()
                         summarize=1
                     elif [ "${filter}" = "" ]
                     then
-                        echo ${logline}
+                        echo "${logline}"
                     fi
                     ;;
                 *)
                     # if no filter, then just print all the lines
                     if [ "${filter}" = "" ]
                     then
-                        echo ${logline}
+                        echo "${logline}"
                     fi
                     ;;
             esac
         fi
         # once summarize is turned on, echo all remaining lines, which is
         # the trailing summary from borg
-        if [ ${summarize} -eq 1 ]
+        if [ "${summarize}" -eq 1 ]
         then
-            echo ${logline}
+            echo "${logline}"
         fi
-    done < ${LOG_PATH}/${LOG_FILE}
+    done < "${LOG_PATH}/${LOG_FILE}"
 }
 
 # process command line
@@ -292,7 +301,7 @@ while getopts ":lx:emad:p:s:hv" opt; do
             ;;
         d)
             save_log
-            delete_backup ${OPTARG}
+            delete_backup "${OPTARG}"
             exit 0
             ;;
         x)
@@ -313,7 +322,7 @@ while getopts ":lx:emad:p:s:hv" opt; do
             ;;
         p)
             save_log
-            prune_backup ${OPTARG}
+            prune_backup "${OPTARG}"
             exit 0
             ;;
         :)
@@ -324,12 +333,16 @@ while getopts ":lx:emad:p:s:hv" opt; do
             echo "Invalid option: -${OPTARG}"
             exit 1
             ;;
+        *)
+            echo "getopts error"
+            exit 1
+            ;;
     esac
 done
 
-if [ ${do_extract} -ne 0 ]
+if [ "${do_extract}" -ne 0 ]
 then
-    extract_backup ${do_extract} ${filter}
+    extract_backup "${do_extract}" "${filter}"
 fi
 
 exit 0
diff --git a/bs-verify b/bs-verify
--- a/bs-verify
+++ b/bs-verify
@@ -69,6 +69,7 @@ REPO_CONFIG="bs-repo.cfg"
 CFG_PATH=~/.local/share/bs-scripts
 
 set -e
+shopt -s inherit_errexit
 
 # generate checksums for a directory tree
 # $1 - root location for generating the sums, script will cd here
@@ -87,11 +88,11 @@ generate_sums()
     sumpath=$2
     sumfile=$3
     saved_cwd=$(pwd)
-    cd ${root}
-    rm -f ${sumfile}
+    cd "${root}"
+    rm -f "${sumfile}"
     echo "Generating sums for: ${root} / ${sumpath}"
-    find "${sumpath}" -type f -exec sha256sum "{}" >> ${sumfile} \;
-    cd ${saved_cwd}
+    find "${sumpath}" -type f -exec sh -c 'sha256sum "$1" >> "${sumfile}"' _ {} \;
+    cd "${saved_cwd}"
 }
 
 # verify previously saved checksums on a directory tree
@@ -102,25 +103,25 @@ verify_sums()
 {
     local root sumfile saved_cwd
     echo "Verifying sums ..."
-    root=$1
-    sumfile=$2
+    root="$1"
+    sumfile="$2"
     saved_cwd=$(pwd)
-    cd ${root}
+    cd "${root}"
     if [ "${3}" == "y" ]
     then
-        sha256sum --check ${sumfile}
+        sha256sum --check "${sumfile}"
     else
         # filter out all the "OK" lines
-        sha256sum --check ${sumfile} | grep -v "OK"
+        { sha256sum --check "${sumfile}" || true; } | grep -v "OK"
     fi
-    cd ${saved_cwd}
+    cd "${saved_cwd}"
 }
 
 # given an ID input (which is probably a number), return a file name
 # $1 - ID
 cfg_filename_from_id()
 {
-    echo ${CFG_PATH}/extract_$1.cfg
+    echo "${CFG_PATH}/extract_$1.cfg"
 }
 
 # get a file to be used for the data file storage
@@ -131,12 +132,12 @@ create_cfg_file_id()
     local i filename
     for i in {0..99}
     do
-        filename=$(cfg_filename_from_id ${i})
-        if [ ! -e ${filename} ]
+        filename=$(cfg_filename_from_id "${i}")
+        if [ ! -e "${filename}" ]
         then
-            touch ${filename}
+            touch "${filename}"
             #echo "Generated data file name: ${filename}"
-            echo ${i}
+            echo "${i}"
             return
         fi
     done
@@ -157,14 +158,16 @@ extract_backup()
     local archive_name extract_path timestamp cfgid cfgfile tempdir saved_cwd
     archive_name=$1
     extract_path=$2
-    timestamp=$(date -Iminutes|cut -d - -f1-3)
+    timestamp=$({ date -Iminutes || true; } |cut -d - -f1-3)
     tempdir=$(mktemp -d)
     cfgid=$(create_cfg_file_id)
-    cfgfile=$(cfg_filename_from_id ${cfgid})
-    echo "TIMESTAMP=${timestamp}" > ${cfgfile}
-    echo "ARCHIVE=\"${archive_name}\"" >> ${cfgfile}
-    echo "EXTRACT_PATH=\"${extract_path}\"" >> ${cfgfile}
-    echo "TEMPDIR=${tempdir}" >> ${cfgfile}
+    cfgfile=$(cfg_filename_from_id "${cfgid}")
+    {
+        echo "TIMESTAMP=${timestamp}"
+        echo "ARCHIVE=\"${archive_name}\""
+        echo "EXTRACT_PATH=\"${extract_path}\""
+        echo "TEMPDIR=${tempdir}"
+    } > "${cfgfile}"
     extract_id=${cfgid}
     echo "Extracting borg backup archive: ${archive_name} ; path: ${extract_path}"
 
@@ -172,23 +175,23 @@ extract_backup()
     # these just go into the environment and are used by borg
     # this step assumes we are in the bs-scripts config directory, which
     # should have happened before this fn was called
-    if [ -f ${REPO_CONFIG} ]
+    if [ -f "${REPO_CONFIG}" ]
     then
-        . ${REPO_CONFIG}
+        . "${REPO_CONFIG}"
     else
         echo "Error loading repo config file"
         exit 1
     fi
     # call borg to do the extract (assumes on the path)
     saved_cwd=$(pwd)
-    if [ -d ${tempdir} ]
+    if [ -d "${tempdir}" ]
     then
-        cd ${tempdir}
+        cd "${tempdir}"
     else
         echo "Error switching to temporary directory for archive extraction"
         exit 1
     fi
-    borg extract ::${archive_name} "${extract_path}"
+    borg extract ::"${archive_name}" "${extract_path}"
 }
 
 # list all of the saved test configurations
@@ -197,11 +200,11 @@ list_extracts()
     local id
     for id in {0..99}
     do
-        filename=$(cfg_filename_from_id ${id})
-        if [ -e ${filename} ]
+        filename=$(cfg_filename_from_id "${id}")
+        if [ -e "${filename}" ]
         then
-            . ${filename}
-            echo "${id}: ${TIMESTAMP} | ${ARCHIVE} | ${EXTRACT_PATH}"
+            . "${filename}"
+            echo "${id}: ${TIMESTAMP:?missing} | ${ARCHIVE:?missing} | ${EXTRACT_PATH:?missing}"
         fi
     done
 }
@@ -212,15 +215,21 @@ list_extracts()
 # $1 - test config ID to clean (use -l to see list)
 clean() {
     local id=$1
-    filename=$(cfg_filename_from_id ${id})
-    if [ -e ${filename} ]
+    filename=$(cfg_filename_from_id "${id}")
+    if [ -e "${filename}" ]
     then
-        . ${filename}
-        echo "Attempting to remove temporary directory of extracted backup ..."
-        echo ${TEMPDIR}
-        rm -rf ${TEMPDIR}
-        echo "Removing metadata file"
-        rm -f ${filename}
+        . "${filename}"
+        if [ -n "${TEMPDIR}" ]
+        then
+            echo "Attempting to remove temporary directory of extracted backup ..."
+            echo "${TEMPDIR}"
+            rm -rf "${TEMPDIR}"
+            echo "Removing metadata file"
+            rm -f "${filename}"
+        else
+            echo "Something went wrong, cannot find TEMPDIR"
+            exit 1
+        fi
     fi
 }
 
@@ -228,10 +237,10 @@ clean() {
 # $1 - test config ID (use -l for list)
 summarize() {
     local id=$1
-    filename=$(cfg_filename_from_id ${id})
-    if [ -e ${filename} ]
+    filename=$(cfg_filename_from_id "${id}")
+    if [ -e "${filename}" ]
     then
-        . ${filename}
+        . "${filename}"
         echo ""
         echo "----------------------"
         echo "Summary of test set: ${id}"
@@ -242,7 +251,7 @@ summarize() {
         echo "Location:   ${TEMPDIR}"
         echo "----------------------"
         echo "Storage Usage of Extracted Files:"
-        du -d 0 -h ${TEMPDIR}
+        du -d 0 -h "${TEMPDIR}"
     fi
 }
 
@@ -296,12 +305,12 @@ while getopts ":a:e:t:i:nc:s:lvh" opt; do
             ;;
         c)
             clean_id=${OPTARG}
-            clean ${clean_id}
+            clean "${clean_id}"
             exit 0
             ;;
         s)
             summarize_id=${OPTARG}
-            summarize ${summarize_id}
+            summarize "${summarize_id}"
             exit 0
             ;;
         :)
@@ -310,6 +319,10 @@ while getopts ":a:e:t:i:nc:s:lvh" opt; do
             ;;
         ?)
             echo "Invalid option: -${OPTARG}"
+            exit 1
+            ;;
+        *)
+            echo "optargs error"
             exit 1
             ;;
     esac
@@ -324,7 +337,7 @@ then
         echo "Extracting a backup using the following ..."
         echo "Archive:      ${archive}"
         echo "Extract path: ${extract_path}"
-        extract_backup ${archive} "${extract_path}"
+        extract_backup "${archive}" "${extract_path}"
     else
         echo "In order to extract (-e) you must specify an archive (-a)"
         exit 1
@@ -346,10 +359,10 @@ then
     # the extract_id either came from -i, or from the extract
     if [ -n "${extract_id}" ]
     then
-        cfgfile=$(cfg_filename_from_id ${extract_id})
-        . ${cfgfile}
-        generate_sums ${host_root} "${EXTRACT_PATH}" ${TEMPDIR}/sums.txt
-        verify_sums ${TEMPDIR} ${TEMPDIR}/sums.txt ${noisy}
+        cfgfile=$(cfg_filename_from_id "${extract_id}")
+        . "${cfgfile}"
+        generate_sums "${host_root}" "${EXTRACT_PATH}" "${TEMPDIR}/sums.txt"
+        verify_sums "${TEMPDIR}" "${TEMPDIR}/sums.txt" "${noisy}"
         exit $?
     else
         echo "In order to verify (-t) you need to either extract (-e/-a) or"
