refactor!: changed config files mechanism, verify method, ...
BREAKING CHANGE: old config files no longer used. config files can be
in one of several locations. config files are now generated by bs-backup
instead of being part of the package.

Changed verify mechanism to use rsync to compare trees instead of using
hash sums as before. This was not working correctly.

Added a significant amount of unit tests.

diff --git a/bs-backup b/bs-backup
--- a/bs-backup
+++ b/bs-backup
@@ -25,6 +25,11 @@
 # many parts of this script are lifted from borgbackup help docs
 
 VER="0.3"
+_fullpath="$(realpath "$0")"
+SCRIPT_DIR="$(dirname "${_fullpath}")"
+
+verbose=0
+gendir=""
 
 usage()
 {
@@ -32,18 +37,27 @@ usage()
     echo "Usage:"
     echo "  bs-backup -b SET_NAME [-n compact] [-n prune]"
     echo "  bs-backup -t SET_NAME"
+    echo "  bs-backup -g ( env | xdg | cwd | config | script )"
     echo "  bs-backup -l"
     echo "  bs-backup -v"
+    echo "  bs-backup -V"
     echo "  bs-backup -h"
     echo ""
     echo "Options:"
-    echo "  -h            show help"
-    echo "  -v            show version"
-    echo "  -l            list available backup set configurations"
     echo "  -b SET_NAME   backup the configuration named SET_NAME"
     echo "  -t SET_NAME   dry-run backup of SET_NAME"
     echo "  -n prune      skip prune operation"
     echo "  -n compact    skip compact operation"
+    echo "  -g            generate config script templates ..."
+    echo "     env        in BS_SCRIPTS_CONFIG"
+    echo "     xdg        in XDG_CONFIG_HOME/bs-scripts"
+    echo "     cwd        in the current directory"
+    echo "     config     in ~/.config/bs-scripts"
+    echo "     script     in the directory containing this script"
+    echo "  -l            list available backup set configurations"
+    echo "  -v            verbose - show extra debugging messages"
+    echo "  -V            show version"
+    echo "  -h            show help"
     echo ""
 }
 
@@ -52,8 +66,274 @@ info()
     printf "%s %s\n" "$( date || true )" "$*" >&2;
 }
 
+# print a thing if verbose is enabled
+# $1 - string to print
+dbg_print()
+{
+    local msg
+    msg="$1"
+    if [ ${verbose} -eq 1 ]
+    then
+        echo "${msg}"
+    fi
+}
+
+# determine where to look for configuration stuff
+# order of precedence
+# - BS_SCRIPTS_CONFIG - user defines in the environment, use this if defined
+# - CWD - if starting dir contains bs-repo.cfg, use that for config
+# - XDG_CONFIG_HOME/bs-scipts - if defined use this location
+# - ~/.config/bs-scripts - look here by default if nothing else defined
+# - script dir - final fallback
+get_config()
+{
+    dbg_print "Determining configuration files location ..."
+    if [ -n "${BS_SCRIPTS_CONFIG}" ]
+    then
+        # preferred config dir is in the env
+        dbg_print "Using user defined BS_SCRIPTS_CONFIG as config location"
+    elif [ -f "bs-repo.cfg" ]
+    then
+        # found a repo config in the current dir, use that
+        BS_SCRIPTS_CONFIG="$(pwd)"
+        dbg_print "Using current directory for configuration"
+    elif [ -n "${XDG_CONFIG_HOME}" ] && [ -f "${XDG_CONFIG_HOME}/bs-scripts/bs-repo.cfg" ]
+    then
+        # XDG_CONFIG_HOME exists, so if repo config is there, use that
+        BS_SCRIPTS_CONFIG="${XDG_CONFIG_HOME}/bs-scripts"
+        dbg_print "Using XDG_CONFIG_HOME for configuration"
+    elif [ -f "~/.config/bs-scripts/bs-repo.cfg" ]
+    then
+        # found repo config in ~/.config ...
+        BS_SCRIPTS_CONFIG=$(realpath "~/.config/bs-scripts")
+        dbg_print "Using local config"
+    else
+        # try the scripts dir
+        BS_SCRIPTS_CONFIG="$(realpath ${SCRIPT_DIR})"
+        dbg_print "Using scripts dir"
+    fi
+
+    dbg_print "I think my configuration is here:"
+    dbg_print "[${BS_SCRIPTS_CONFIG}]"
+    REPO_CONFIG_FILE="${BS_SCRIPTS_CONFIG}/bs-repo.cfg"
+    if [ -f "${REPO_CONFIG_FILE}" ]
+    then
+        dbg_print "Using config: ${REPO_CONFIG_FILE}"
+    else
+        echo "I could not find configuration file:"
+        echo "[${REPO_CONFIG_FILE}]"
+        exit 1
+    fi
+}
+
+# generate template config files
+# $1 - location
+#      - env - use BS_SCRIPTS_CONFIG
+#      - xdg - use XDG_CONFIG_HOME/bs-scripts
+#      - cwd - use CWD
+#      - config - use ~/.config/bs-scripts
+#      - script - use script dir
+#
+generate_configs()
+{
+    local loc configdir
+    loc="$1"
+
+    if [ "${loc}" = "env" ]
+    then
+        if [ -n "${BS_SCRIPTS_CONFIG}" ]
+        then
+            configdir="${BS_SCRIPTS_CONFIG}"
+        else
+            echo "you specified 'env' but BS_SCRIPTS_CONFIG is not defined"
+            exit 1
+        fi
+    elif [ "${loc}" = "xdg" ]
+    then
+        if [ -n "${XDG_CONFIG_HOME}" ]
+        then
+            configdir="${XDG_CONFIG_HOME}/bs-scripts"
+            mkdir -p "${configdir}" || { echo "could not create ${configdir}"; exit 1; }
+        else
+            echo "you specified 'xdg' but XDG_CONFIG_HOME is not defined"
+            exit 1
+        fi
+    elif [ "${loc}" = "cwd" ]
+    then
+        configdir=$(realpath $(pwd))
+    elif [ "${loc}" = "config" ]
+    then
+        configdir="$(dirname ${HOME}/.config/bs-scripts/x)"
+        mkdir -p "${configdir}" || { echo "could not create ${configdir}"; exit 1; }
+    elif [ "${loc}" = "script" ]
+    then
+        configdir="${SCRIPT_DIR}"
+    else
+        echo "unrecognized config location: ${loc}"
+        exit 1
+    fi
+
+    dbg_print "Using config dir: ${configdir}"
+
+    # BS-REPO.CFG
+
+    if [ -f "${configdir}/bs-repo.cfg" ]
+    then
+        echo "NOT GENERATING: ${configdir}/bs-repo.cfg because it already exists."
+    else
+        cat <<BSREPOCFG > "${configdir}/bs-repo.cfg"
+# Generated Template bs-repo.cfg for bs-scripts
+# Modify this file for your setup
+#
+# REPO
+#
+# BORG_REPO is the path to your borg repository, local or remote
+# below is an example Hetnzer storage box path
+#
+# fix up the URL and uncomment
+
+# export BORG_REPO=ssh://uxxxxxx@uxxxxxx.your-storagebox.de:23/./backups/\$(hostname -s)
+
+# one of BORG_PASSPHRASE or BORG_PASSCOMMAND should be defined
+# see the borg docs
+#
+# example PASSPHRASE from borg docs
+
+# export BORG_PASSPHRASE='XYZl0ngandsecurepa_55_phrasea&&123'
+
+# example PASSCOMMAND for repo passphrase stored in mac keychain
+
+# export BORG_PASSCOMMAND="security find-generic-password -a \$USER -s borg-\$(hostname -s)-passphrase -w"
+
+# if you want to create the password for mac keychain, you can do something
+# like this:
+#
+#    security add-generic-password -a \$USER -s borg-\$(hostname -s)-passphrase -w 'your_password_here'
+#
+# You only have to do that once and then the password is stored in your Mac
+# keychain. However it would be a good idea to also store that same password in
+# your password manager (if it's not keychain).
+#
+# Be aaware that if you type your password in the clear as in above, it may be
+# stored in your shell history file (~/.bash_history). So be sure and delete
+# that out of your history or supply the password using another method.
+#
+# LOGS
+#
+# This section defines where log files are created. Log files are created when
+# a backup runs under the agent, which is set up using 'bs-agent'.
+# The logs can be viewed with 'bs-logs'.
+#
+# Fix up the path and file name as needed and uncomment. This example below
+# is probably what you need for MacOS
+
+# export BS_LOG_PATH="\${HOME}/Library/Logs"
+# export BS_LOG_FILE="bs-backup.log"
+#
+# VERIFY
+#
+# This section defines where verify data sets metadata are stored.
+# This is used by the bs-verify script. When you use bs-verify, information
+# about the backup set is stored at this location.
+#
+# Fix up the path as needed and uncomment.
+#
+# export BS_VERIFY_CFG_PATH="\${HOME}/.local/share/bs-scripts"
+BSREPOCFG
+        echo "Generated: ${configdir}/bs-repo.cfg"
+    fi
+
+    # BS-COMMON-EXCLUDE.CFG
+
+    if [ -f "${configdir}/bs-exclude-common.cfg" ]
+    then
+        echo "NOT GENERATING: ${configdir}/bs-exclude-common.cfg because it already exists."
+    else
+        cat <<BSEXCLUDE > "${configdir}/bs-exclude-common.cfg"
+# Generated template bs-exclude-common.cfg for bs-scripts
+# Modify this file for your setup
+#
+# This is a list of exclude patterns/files that should apply to all backups
+# See the borg documentation for the exclude format
+#
+sh:**/venv
+*/Downloads*
+*/Automatically*
+*/.DS_*
+*/.DocumentRevisions*
+*/Spotlight*
+*/TemporaryItems
+*/.Trashes
+*/.fseventsd
+*/tmp
+*/temp
+*/cache*
+*/Cache*
+*/.cache
+*/.Trash
+*/Logs
+*/.MobileBackups*
+*/MobileBackups*
+BSEXCLUDE
+        echo "Generated: ${configdir}/bs-exclude-common.cfg"
+    fi
+
+    # BS-SET-EXAMPLE.CFG
+
+    if [ -f "${configdir}/bs-set-example.cfg" ]
+    then
+        echo "NOT GENERATING: ${configdir}/bs-set-example.cfg because it already exists."
+    else
+        cat <<BSSETEXAMPLE > "${configdir}/bs-set-example.cfg"
+# Generated template bs-set-example.cfg for bs-scripts
+# Modify this file or make new copies for your setup
+#
+# This file defines a backup set. You can have more than one of these kind of
+# files. They should be named 'bs-set-name.cfg' where 'name' is the name of
+# the backup set.
+#
+# bs-backup backup set configuration file
+#
+# optional description. can be left empty.
+# use a very short string, it will be shown when backup configs are listed
+#
+BACKUP_SET_DESCRIPTION="Example backup set"
+
+# BACKUP_CUSTOM_FLAGS is mainly used to list paths/patterns to exclude for
+# this backup set. It does not need to list the common exclusions, just
+# exclusions unique to this backup set.
+#
+# See the borg docs for how to specify the patterns. But they often look like
+# this:
+#     */foobar*
+#
+# It can be empty if there are no special exclusions.
+# It can also include other borg flags if needed.
+# This example shows excluding two paths.
+#
+BACKUP_CUSTOM_FLAGS="--exclude 'bs-repo.cfg' --exclude '*/.git'"
+
+# BACKUP_SOURCE PATHS must have at least one path. it can have more than one
+# path, space separated, or on separate lines as described above. Normally this
+# should be a full path, such as:
+#     BACKUP_SOURCE_PATHS="/Users/joe/Documents"
+#
+# In this example, it just uses the current directory so that you can use it to
+# do an example backup of this directory.
+#
+BACKUP_SOURCE_PATHS="."
+BSSETEXAMPLE
+        echo "Generated: ${configdir}/bs-set-example.cfg"
+    fi
+}
+
+# list all the available backup configuration
+# configuration is established before this is called
 list()
 {
+    local cwd
+    cwd="$(pwd)"
+    cd "${BS_SCRIPTS_CONFIG}"
     echo ""
     echo "Available backup configurations"
     echo "-------------------------------"
@@ -65,12 +345,10 @@ list()
         printf "%-16s %s\n" "${setname}" "${BACKUP_SET_DESCRIPTION}"
     done
     echo ""
+    cd "${cwd}" || { echo "Could not cd to ${cwd}"; exit 1; }
 }
 
 trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
-
-# switch to script directory
-cd "$(dirname "$0")" || { echo "error cd to script directory"; exit 1; }
 
 # initialize prune and compact defaults
 doprune=1
@@ -94,20 +372,22 @@ fi
 # otherwise, process the options
 # this does not do a lot of cross checking of options so it is possible
 # to specify nonsense set of options
-while getopts ":lvhb:t:n:" opt; do
+while getopts ":lvVhb:t:n:g:" opt; do
     case ${opt} in
         h)
             usage
             exit 0
             ;;
-        v)
+        V)
             echo "bs-backup from bs-scripts package ${VER}"
             echo "https://github.com/kroesche/bs-scripts"
             exit 0
             ;;
+        v)
+            verbose=1
+            ;;
         l)
-            list
-            exit 0
+            action="list"
             ;;
         b)
             if [ "${action}" = "test" ]
@@ -140,6 +420,11 @@ while getopts ":lvhb:t:n:" opt; do
                 info "requested skip compacting"
             fi
             ;;
+        g)
+            gendir=${OPTARG}
+            generate_configs "${gendir}"
+            exit 0
+            ;;
         :)
             echo "Option -${OPTARG} requires an argument"
             exit 1
@@ -154,6 +439,15 @@ while getopts ":lvhb:t:n:" opt; do
             ;;
     esac
 done
+
+# remaining commands require access to configuration file
+get_config
+
+if [ "${action}" = "list" ]
+then
+    list
+    exit 0
+fi
 
 # determine command action
 # --stats and --dry-run are not compatible switches for borg
@@ -198,18 +492,22 @@ fi
 
 info "using set name: ${setname}, action: ${action}"
 
-# determine configuration file names
+# determine configuration files
 #
-# repo_config contains the definitions of the BORG_REPO env variables.
-# It should define BORG_REPO and BORG_PASSPHRASE or BORG_PASSCOMMAND
-# these should be exports so the file can be sourced
+# REPO_CONFIG_FILE was set by get_config already
 #
-repo_config_file="bs-repo.cfg"        # BORG_REPO, etc
+# BS_SCRIPTS_CONFIG is the path where all the other config files should be
 
 # common exclude is a list of files/folders to exclude using the borg
 # pattern style. one exclusion per line in the file
 #
-common_exclude_file="bs-exclude-common.txt"
+# make sure there is at least a default file present in the config
+COMMON_EXCLUDE_FILE="${BS_SCRIPTS_CONFIG}/bs-exclude-common.cfg"
+if [ ! -f "${COMMON_EXCLUDE_FILE}" ]
+then
+    info "No exclude file found: ${COMMON_EXCLUDE_FILE}"
+    exit 1
+fi
 
 # set_config is the config file for the specific backup set
 # it is of the form:
@@ -228,15 +526,15 @@ common_exclude_file="bs-exclude-common.txt"
 # * BACKUP_SOURCE_PATHS must have at least one path, but can have more than one
 # * the file can have comments on lines by themselves
 #
-set_config_file="bs-set-${setname}.cfg"
+SET_CONFIG_FILE="${BS_SCRIPTS_CONFIG}/bs-set-${setname}.cfg"
 
 # make sure backup set is valid based on existence of a config file
-if [ -f "${set_config_file}" ]
+if [ -f "${SET_CONFIG_FILE}" ]
 then
     # read in (source) the custom backup variables
-    . "./${set_config_file}"
+    . "${SET_CONFIG_FILE}"
 else
-    info "No config file found for backup set: ${set_config_file}"
+    info "No config file found for backup set: ${SET_CONFIG_FILE}"
     exit 1
 fi
 
@@ -261,11 +559,11 @@ else
 fi
 
 # validate and source the repo credentials
-if [ -f "${repo_config_file}" ]
+if [ -f "${REPO_CONFIG_FILE}" ]
 then
-    . "./${repo_config_file}"
+    . "${REPO_CONFIG_FILE}"
 else
-    info "No repo config file found: ${repo_config_file}"
+    info "No repo config file found: ${REPO_CONFIG_FILE}"
     exit 1
 fi
 
@@ -287,11 +585,15 @@ info "BORG_PASS... is not shown for security"
 # my mac
 #
 # assemble all the common and custom command line args into one variable
+ARCHIVE="${BORG_REPO}::{hostname}-${setname}-{now}"
 BORG_CLI_ARGS="create
 --verbose --list --show-rc --compression zstd,9 --exclude-caches --exclude-nodump
-${filter} ${action_switch}
---exclude-from ${common_exclude_file}
-${BACKUP_CUSTOM_FLAGS} ::{hostname}-${setname}-{now} ${BACKUP_SOURCE_PATHS}"
+${filter}
+${action_switch}
+--exclude-from ${COMMON_EXCLUDE_FILE}
+${BACKUP_CUSTOM_FLAGS}
+${ARCHIVE}
+${BACKUP_SOURCE_PATHS}"
 
 # show what will be called
 info "BORG_CLI_ARGS:"
@@ -300,6 +602,8 @@ info "${BORG_CLI_ARGS}"
 info "+++BACKUP: ${setname}"
 # use xargs to expand args and pass to borg. this seems to work
 echo "${BORG_CLI_ARGS}" | xargs "${BORG}"
+
+backup_exit=$?
 
 info "---BACKUP"
 
@@ -310,8 +614,6 @@ then
     exit 0
 fi
 
-backup_exit=$?
-
 if [ "${doprune}" = 1 ]
 then
     info "+++PRUNE"
@@ -319,7 +621,8 @@ then
     ${BORG} prune --list --glob-archives "{hostname}-${setname}-*" --show-rc    \
         --keep-daily 7                  \
         --keep-weekly 4                 \
-        --keep-monthly 6
+        --keep-monthly 6                \
+        "${BORG_REPO}"
     prune_exit=$?
     info "---PRUNE"
 else
@@ -331,7 +634,7 @@ if [ "${docompact}" = 1 ]
 then
     info "+++COMPACTING"
 
-    ${BORG} compact
+    ${BORG} compact "${BORG_REPO}"
     compact_exit=$?
     info "---COMPACTING"
 else
diff --git a/bs-logs b/bs-logs
--- a/bs-logs
+++ b/bs-logs
@@ -27,10 +27,9 @@
 
 VER="0.3"
 
-#LOG_PATH="."
-LOG_PATH="${HOME}/Library/Logs"
-LOG_FILE="bs-backup.log"
-TMPFILE="${LOG_FILE}.tmp"
+verbose=0
+_fullpath="$(realpath "$0")"
+SCRIPT_DIR="$(dirname "${_fullpath}")"
 
 usage()
 {
@@ -44,7 +43,7 @@ Usage:
   bs-logs -x SET_ID [ -e | -m | -a ]
   bs-logs -d SET_ID
   bs-logs -p N
-  bs-logs -v
+  bs-logs -V
   bs-logs -h
 
 Options:
@@ -56,7 +55,8 @@ Options:
   -a            with -x, show added files in backup
   -d SET_ID     delete backup set data from log file (reduces log size)
   -p N          prune log keeping N most recent backup sets log data
-  -v            show version
+  -v            verbose - show extra debugging messages (must be first opt)
+  -V            show version
   -h            show help
 
 Only one of -e/-m/-a can be used at a time.
@@ -64,10 +64,93 @@ Only one of -e/-m/-a can be used at a time.
 USAGE
 }
 
+# print a thing if verbose is enabled
+# $1 - string to print
+dbg_print()
+{
+    local msg
+    msg="$1"
+    if [ "${verbose}" -eq 1 ]
+    then
+        echo "${msg}"
+    fi
+}
+
+# determine where to look for configuration stuff
+# order of precedence
+# - BS_SCRIPTS_CONFIG - user defines in the environment, use this if defined
+# - CWD - if starting dir contains bs-repo.cfg, use that for config
+# - XDG_CONFIG_HOME/bs-scipts - if defined use this location
+# - ~/.config/bs-scripts - look here by default if nothing else defined
+# - script dir - final fallback
+#
+# sets BS_SCRIPTS_CONFIG and REPO_CONFIG_FILE
+get_config()
+{
+    dbg_print "Determining configuration files location ..."
+    if [ -n "${BS_SCRIPTS_CONFIG}" ]
+    then
+        # preferred config dir is in the env
+        dbg_print "Using user defined BS_SCRIPTS_CONFIG as config location"
+    elif [ -f "bs-repo.cfg" ]
+    then
+        # found a repo config in the current dir, use that
+        BS_SCRIPTS_CONFIG="$(pwd)"
+        dbg_print "Using current directory for configuration"
+    elif [ -n "${XDG_CONFIG_HOME}" ] && [ -f "${XDG_CONFIG_HOME}/bs-scripts/bs-repo.cfg" ]
+    then
+        # XDG_CONFIG_HOME exists, so if repo config is there, use that
+        BS_SCRIPTS_CONFIG="${XDG_CONFIG_HOME}/bs-scripts"
+        dbg_print "Using XDG_CONFIG_HOME for configuration"
+    elif [ -f "${HOME}/.config/bs-scripts/bs-repo.cfg" ]
+    then
+        # found repo config in ~/.config ...
+        BS_SCRIPTS_CONFIG="$(realpath "${HOME}")/.config/bs-scripts"
+        dbg_print "Using local config"
+    else
+        # try the scripts dir
+        BS_SCRIPTS_CONFIG="$(realpath "${SCRIPT_DIR}")"
+        dbg_print "Using scripts dir"
+    fi
+
+    dbg_print "I think my configuration is here:"
+    dbg_print "[${BS_SCRIPTS_CONFIG}]"
+    REPO_CONFIG_FILE="${BS_SCRIPTS_CONFIG}/bs-repo.cfg"
+    if [ -f "${REPO_CONFIG_FILE}" ]
+    then
+        dbg_print "Using config: ${REPO_CONFIG_FILE}"
+    else
+        echo "I could not find configuration file:"
+        echo "[${REPO_CONFIG_FILE}]"
+        exit 1
+    fi
+
+    # get the log file config from repo config file
+    # REPO_CONFIG_FILE is known to exist at this point
+    . "${REPO_CONFIG_FILE}"
+    if [ -z "${BS_LOG_PATH}" ]
+    then
+        echo "BS_LOG_PATH is not defined"
+        exit 1
+    else
+        dbg_print "Using BS_LOG_PATH: ${BS_LOG_PATH}"
+    fi
+    if [ -z "${BS_LOG_FILE}" ]
+    then
+        echo "BS_LOG_FILE is not defined"
+        exit 1
+    else
+        dbg_print "Using BS_LOG_FILE: ${BS_LOG_FILE}"
+    fi
+}
+
 # scan log for start markers, echo to console
+# $1 - log file path/file
 list_backups()
 {
     local set_id=1
+    local logfile="$1"
+
     while read -r logline
     do
         case "${logline}" in
@@ -78,16 +161,21 @@ list_backups()
             *)
                 ;;
         esac
-    done < "${LOG_PATH}/${LOG_FILE}"
+    done < "${logfile}"
 }
 
 # copy log to tmp file, except lines which match requested backup number
 # after tmp file is finished, copy back to main log file
+# $1 - log file path/file
+# $2 - requested set
 delete_backup()
 {
-    local requested_set="$1"
+    local requested_set="$2"
     local set_id=0
+    local logfile="$1"
+
     echo "DELETE: ${requested_set}"
+    echo "logfile: ${logfile}"
 
     while read -r logline
     do
@@ -111,23 +199,28 @@ delete_backup()
         # so those line are "deleted"
         if [ "${set_id}" -ne "${requested_set}" ]
         then
-            echo "${logline}" >> "${TMPFILE}"
+            echo "${logline}" >> "${logfile}.tmp"
         fi
-    done < "${LOG_PATH}/${LOG_FILE}"
-    cp "${TMPFILE}" "${LOG_PATH}/${LOG_FILE}"
-    rm "${TMPFILE}"
+    done < "${logfile}"
+    cp "${logfile}.tmp" "${logfile}"
+    rm "${logfile}.tmp"
 }
 
 # make a "backup" copy of the backup log
+# $1 - log file path/file
 save_log()
 {
-    cp "${LOG_PATH}/${LOG_FILE}" "${LOG_PATH}/${LOG_FILE}.0"
+    local logfile="$1"
+    cp "${logfile}" "${logfile}.0"
 }
 
 # remove all but the last N backups from the log
+# $1 - log file path/file
+# $2 - number remaining
 prune_backup()
 {
-    local set_id=$((0 - $1))
+    local set_id=$((0 - $2))
+    local logfile="$1"
 
     # count number of backup sets in the log
     while read -r logline
@@ -139,30 +232,32 @@ prune_backup()
             *)
                 ;;
         esac
-    done < "${LOG_PATH}/${LOG_FILE}"
+    done < "${logfile}"
     # set_id has the number of backups that need to be deleted
     # delete 0 first to get rid of any leading cruft
-    delete_backup 0
+    delete_backup "${logfile}" 0
     # delete first backup for as many as needed
     # this is inefficent and should be improved, but works
     while [ "${set_id}" -gt 0 ]
     do
-        delete_backup 1
+        delete_backup "${logfile}" 1
         set_id=$((set_id - 1))
     done
 }
 
 # extract data about a backup, with various options
-# $1 is the set number to extract (numbers from -l)
-# $2 is a filter value
+# $1 - log file path/file
+# $2 is the set number to extract (numbers from -l)
+# $3 is a filter value
 # * a - print lines of added files
 # * m - print lines of modified files
 # * e - print lines of error files
 # * s - print just a summary of the backup set
 extract_backup()
 {
-    local requested_set="$1"
-    local filter="$2"
+    local logfile="$1"
+    local requested_set="$2"
+    local filter="$3"
     local set_id=1
     local extracting=0
     local summarize=0
@@ -264,7 +359,7 @@ extract_backup()
         then
             echo "${logline}"
         fi
-    done < "${LOG_PATH}/${LOG_FILE}"
+    done < "${logfile}"
 }
 
 # process command line
@@ -284,24 +379,29 @@ fi
 
 do_extract=0
 
-while getopts ":lx:emad:p:s:hv" opt; do
+while getopts ":lx:emad:p:s:hvV" opt; do
     case ${opt} in
         h)
             usage
             exit 0
             ;;
-        v)
+        V)
             echo "bs-logs from bs-scripts package ${VER}"
             echo "https://github.com/kroesche/bs-scripts"
             exit 0
             ;;
+        v)
+            verbose=1
+            ;;
         l)
-            list_backups
+            get_config
+            list_backups "${BS_LOG_PATH}/${BS_LOG_FILE}"
             exit 0
             ;;
         d)
-            save_log
-            delete_backup "${OPTARG}"
+            get_config
+            save_log "${BS_LOG_PATH}/${BS_LOG_FILE}"
+            delete_backup "${BS_LOG_PATH}/${BS_LOG_FILE}" "${OPTARG}"
             exit 0
             ;;
         x)
@@ -321,8 +421,9 @@ while getopts ":lx:emad:p:s:hv" opt; do
             filter="s"
             ;;
         p)
-            save_log
-            prune_backup "${OPTARG}"
+            get_config
+            save_log "${BS_LOG_PATH}/${BS_LOG_FILE}"
+            prune_backup "${BS_LOG_PATH}/${BS_LOG_FILE}" "${OPTARG}"
             exit 0
             ;;
         :)
@@ -340,9 +441,12 @@ while getopts ":lx:emad:p:s:hv" opt; do
     esac
 done
 
+# determine config file locations
+get_config
+
 if [ "${do_extract}" -ne 0 ]
 then
-    extract_backup "${do_extract}" "${filter}"
+    extract_backup "${BS_LOG_PATH}/${BS_LOG_FILE}" "${do_extract}" "${filter}"
 fi
 
 exit 0
diff --git a/bs-verify b/bs-verify
--- a/bs-verify
+++ b/bs-verify
@@ -24,18 +24,22 @@
 #
 VER="0.3"
 
+verbose=0
+_fullpath="$(realpath "$0")"
+SCRIPT_DIR="$(dirname "${_fullpath}")"
+
 usage() {
     cat <<USAGE
 
 Verify borg backups.
 
 Usage:
-  bs-verify -a ARCHIVE -e EXTRACT_PATH [ -t HOST_ROOT ] [ -n ]
+  bs-verify  -a ARCHIVE -e EXTRACT_PATH [ -t HOST_ROOT ] [ -n ]
   bs-verify -i EXTRACT_ID -t HOST_PATH [ -n ]
   bs-verify -l
   bs-verify -s EXTRACT_ID
   bs-verify -c EXTRACT_ID
-  bs-verify -v
+  bs-verify -V
   bs-verify -h
 
 Options:
@@ -48,7 +52,8 @@ Options:
   -l                list all cached extracted data sets
   -c EXTRACT_ID     delete all saved data for the specified ID, see '-l'
   -s EXTRACT_ID     show all details of a particular extracted backup set
-  -v                show version
+  -v                verbose - show extra debugging messages (must be first opt)
+  -V                show version
   -h                show help
 
 Example:
@@ -60,68 +65,111 @@ See the man page for more details and examples.
 USAGE
 }
 
-# repo configuration, path to repo and credentials
-# assumes in bs-scripts config directory
-REPO_CONFIG="bs-repo.cfg"
+# print a thing if verbose is enabled
+# $1 - string to print
+dbg_print()
+{
+    local msg
+    msg="$1"
+    if [ "${verbose}" -eq 1 ]
+    then
+        echo "${msg}"
+    fi
+}
 
-# where extract configurations are saved
-# TODO make this configurable
-CFG_PATH=~/.local/share/bs-scripts
+# determine where to look for configuration stuff
+# order of precedence
+# - BS_SCRIPTS_CONFIG - user defines in the environment, use this if defined
+# - CWD - if starting dir contains bs-repo.cfg, use that for config
+# - XDG_CONFIG_HOME/bs-scipts - if defined use this location
+# - ~/.config/bs-scripts - look here by default if nothing else defined
+# - script dir - final fallback
+#
+# sets BS_SCRIPTS_CONFIG and REPO_CONFIG_FILE
+get_config()
+{
+    dbg_print "Determining configuration files location ..."
+    if [ -n "${BS_SCRIPTS_CONFIG}" ]
+    then
+        # preferred config dir is in the env
+        dbg_print "Using user defined BS_SCRIPTS_CONFIG as config location"
+    elif [ -f "bs-repo.cfg" ]
+    then
+        # found a repo config in the current dir, use that
+        BS_SCRIPTS_CONFIG="$(pwd)"
+        dbg_print "Using current directory for configuration"
+    elif [ -n "${XDG_CONFIG_HOME}" ] && [ -f "${XDG_CONFIG_HOME}/bs-scripts/bs-repo.cfg" ]
+    then
+        # XDG_CONFIG_HOME exists, so if repo config is there, use that
+        BS_SCRIPTS_CONFIG="${XDG_CONFIG_HOME}/bs-scripts"
+        dbg_print "Using XDG_CONFIG_HOME for configuration"
+    elif [ -f "${HOME}/.config/bs-scripts/bs-repo.cfg" ]
+    then
+        # found repo config in ~/.config ...
+        BS_SCRIPTS_CONFIG="$(realpath "${HOME}")/.config/bs-scripts"
+        dbg_print "Using local config"
+    else
+        # try the scripts dir
+        BS_SCRIPTS_CONFIG="$(realpath "${SCRIPT_DIR}")"
+        dbg_print "Using scripts dir"
+    fi
+
+    dbg_print "I think my configuration is here:"
+    dbg_print "[${BS_SCRIPTS_CONFIG}]"
+    REPO_CONFIG_FILE="${BS_SCRIPTS_CONFIG}/bs-repo.cfg"
+    if [ -f "${REPO_CONFIG_FILE}" ]
+    then
+        dbg_print "Using config: ${REPO_CONFIG_FILE}"
+    else
+        echo "I could not find configuration file:"
+        echo "[${REPO_CONFIG_FILE}]"
+        exit 1
+    fi
+
+    # get the log file config from repo config file
+    # REPO_CONFIG_FILE is known to exist at this point
+    . "${REPO_CONFIG_FILE}"
+    if [ -z "${BS_VERIFY_CFG_PATH}" ]
+    then
+        echo "BS_VERIFY_CFG_PATH is not defined"
+        exit 1
+    else
+        dbg_print "Using BS_VERIFY_CFG_PATH: ${BS_VERIFY_CFG_PATH}"
+    fi
+}
 
 set -e
 shopt -s inherit_errexit
 
-# generate checksums for a directory tree
-# $1 - root location for generating the sums, script will cd here
-# $2 - path over which to generate checksums
-# $3 - location of checksum file
-#
-# example:
-#   root location - /
-#   path - Users/joe/Documents
-#   file - (temp file where sums are saved)
-generate_sums()
+# compare two trees and list different files
+# $1 - from path (the original tree)
+# $2 - compare path (the extracted backup files)
+compare_trees()
 {
-    local root sumfile saved_cwd sumpath
-
-    root=$1
-    sumpath=$2
-    sumfile=$3
-    saved_cwd=$(pwd)
-    cd "${root}"
-    rm -f "${sumfile}"
-    echo "Generating sums for: ${root} / ${sumpath}"
-    find "${sumpath}" -type f -exec sh -c 'sha256sum "$1" >> "${sumfile}"' _ {} \;
-    cd "${saved_cwd}"
-}
-
-# verify previously saved checksums on a directory tree
-# $1 - root location of the files to check
-# $2 - location of checksum file
-# $3 - noisy flag - show all checksum output (otherwise only errors)
-verify_sums()
-{
-    local root sumfile saved_cwd
-    echo "Verifying sums ..."
-    root="$1"
-    sumfile="$2"
-    saved_cwd=$(pwd)
-    cd "${root}"
-    if [ "${3}" == "y" ]
+    local originals extracts output
+    originals="$1/"
+    extracts="$2/"
+    echo "-----------------------"
+    echo "Originals: ${originals}"
+    echo "Extracted: ${extracts}"
+    echo "-----------------------"
+    output=$(rsync -Rrnc --out-format="%f" "${originals}" "${extracts}")
+    if [ -z "${output}" ]
     then
-        sha256sum --check "${sumfile}"
+        echo "All files verified"
+        return 0
     else
-        # filter out all the "OK" lines
-        { sha256sum --check "${sumfile}" || true; } | grep -v "OK"
+        echo "The following files are missing or changed in the backup data:"
+        echo "${output}"
+        return 1
     fi
-    cd "${saved_cwd}"
 }
 
 # given an ID input (which is probably a number), return a file name
 # $1 - ID
 cfg_filename_from_id()
 {
-    echo "${CFG_PATH}/extract_$1.cfg"
+    echo "${BS_VERIFY_CFG_PATH}/extract_$1.cfg"
 }
 
 # get a file to be used for the data file storage
@@ -149,13 +197,15 @@ create_cfg_file_id()
 # $1 - archive name
 # $2 - path to extract
 #
-# returns - extraction ID, can be used elsehwere
+# returns - extraction ID, can be used elsewere
 #
-# creates an extraction config file in the CFG_PATH that contains info
+# creates an extraction config file in the BS_VERIFY_CFG_PATH that contains info
 # about this extraction, and returns an ID referencing that file
 extract_backup()
 {
     local archive_name extract_path timestamp cfgid cfgfile tempdir saved_cwd
+    # extract_id is kept global because it is needed in another part of
+    # the script
     archive_name=$1
     extract_path=$2
     timestamp=$({ date -Iminutes || true; } |cut -d - -f1-3)
@@ -175,9 +225,9 @@ extract_backup()
     # these just go into the environment and are used by borg
     # this step assumes we are in the bs-scripts config directory, which
     # should have happened before this fn was called
-    if [ -f "${REPO_CONFIG}" ]
+    if [ -f "${REPO_CONFIG_FILE}" ]
     then
-        . "${REPO_CONFIG}"
+        . "${REPO_CONFIG_FILE}"
     else
         echo "Error loading repo config file"
         exit 1
@@ -191,7 +241,7 @@ extract_backup()
         echo "Error switching to temporary directory for archive extraction"
         exit 1
     fi
-    borg extract ::"${archive_name}" "${extract_path}"
+    borg extract -v --debug  "${BORG_REPO}::${archive_name}" "${extract_path}"
 }
 
 # list all of the saved test configurations
@@ -270,21 +320,22 @@ then
     exit 0
 fi
 
-# switch to script directory
-cd "$(dirname "$0")"
-
-while getopts ":a:e:t:i:nc:s:lvh" opt; do
+while getopts ":a:e:t:i:nc:s:lvVh" opt; do
     case ${opt} in
         h)
             usage
             exit 0
             ;;
-        v)
+        V)
             echo "bs-verify from bs-scripts package ${VER}"
             echo "https://github.com/kroesche/bs-scripts"
             exit 0
             ;;
+        v)
+            verbose=1
+            ;;
         l)
+            get_config
             list_extracts
             exit 0
             ;;
@@ -304,11 +355,13 @@ while getopts ":a:e:t:i:nc:s:lvh" opt; do
             noisy="y"
             ;;
         c)
+            get_config
             clean_id=${OPTARG}
             clean "${clean_id}"
             exit 0
             ;;
         s)
+            get_config
             summarize_id=${OPTARG}
             summarize "${summarize_id}"
             exit 0
@@ -328,6 +381,9 @@ while getopts ":a:e:t:i:nc:s:lvh" opt; do
     esac
 done
 
+# determine config file location
+get_config
+
 # user is requesting an extract
 if [ -n "${extract_path}" ]
 then
@@ -338,6 +394,7 @@ then
         echo "Archive:      ${archive}"
         echo "Extract path: ${extract_path}"
         extract_backup "${archive}" "${extract_path}"
+        extract_err=$?
     else
         echo "In order to extract (-e) you must specify an archive (-a)"
         exit 1
@@ -361,20 +418,25 @@ then
     then
         cfgfile=$(cfg_filename_from_id "${extract_id}")
         . "${cfgfile}"
-        generate_sums "${host_root}" "${EXTRACT_PATH}" "${TEMPDIR}/sums.txt"
-        verify_sums "${TEMPDIR}" "${TEMPDIR}/sums.txt" "${noisy}"
-        exit $?
+        compare_trees "${EXTRACT_PATH}" "${TEMPDIR}"
+        exit 0
     else
         echo "In order to verify (-t) you need to either extract (-e/-a) or"
         echo "specify a test ID (-i) of a previously extracted backup"
         exit 1
     fi
+elif [ -n "${extract_path}" ]
+then
+    # in case we get here, as long as an extract was performed, this can be
+    # a normal exit
+    exit ${extract_err}
 elif [ -n "${extract_id}" ]
 then
     echo "Using -i alone does nothing. You also need -t"
     exit 1
 fi
 
+# logical path that should not occur
 echo "I somehow ended up at the end of the script with nothing to do!"
 echo "There may be a bug in the script."
 exit 1
