feat: more flexible config file location, add tests

diff --git a/bs-backup b/bs-backup
--- a/bs-backup
+++ b/bs-backup
@@ -25,6 +25,9 @@
 # many parts of this script are lifted from borgbackup help docs
 
 VER="0.3"
+SCRIPT_DIR="$(dirname $(realpath "$0"))"
+
+verbose=0
 
 usage()
 {
@@ -34,11 +37,13 @@ usage()
     echo "  bs-backup -t SET_NAME"
     echo "  bs-backup -l"
     echo "  bs-backup -v"
+    echo "  bs-backup -V"
     echo "  bs-backup -h"
     echo ""
     echo "Options:"
     echo "  -h            show help"
-    echo "  -v            show version"
+    echo "  -v            verbose - show extra debugging messages"
+    echo "  -V            show version"
     echo "  -l            list available backup set configurations"
     echo "  -b SET_NAME   backup the configuration named SET_NAME"
     echo "  -t SET_NAME   dry-run backup of SET_NAME"
@@ -52,8 +57,73 @@ info()
     printf "%s %s\n" "$( date || true )" "$*" >&2;
 }
 
+# print a thing if verbose is enabled
+# $1 - string to print
+dbg_print()
+{
+    local msg
+    msg="$1"
+    if [ ${verbose} -eq 1 ]
+    then
+        echo "${msg}"
+    fi
+}
+
+# determine where to look for configuration stuff
+# order of precedence
+# - BS_SCRIPTS_CONFIG - user defines in the environment, use this if defined
+# - CWD - if starting dir contains bs-repo.cfg, use that for config
+# - XDG_CONFIG_HOME/bs-scipts - if defined use this location
+# - ~/.config/bs-scripts - look here by default if nothing else defined
+# - script dir - final fallback
+get_config()
+{
+    dbg_print "Determining configuration files location ..."
+    if [ -n "${BS_SCRIPTS_CONFIG}" ]
+    then
+        # preferred config dir is in the env
+        dbg_print "Using user defined BS_SCRIPTS_CONFIG as config location"
+    elif [ -f "bs-repo.cfg" ]
+    then
+        # found a repo config in the current dir, use that
+        BS_SCRIPTS_CONFIG="$(pwd)"
+        dbg_print "Using current directory for configuration"
+    elif [ -n "${XDG_CONFIG_HOME}" ] && [ -f "${XDG_CONFIG_HOME}/bs-scripts/bs-repo.cfg" ]
+    then
+        # XDG_CONFIG_HOME exists, so if repo config is there, use that
+        BS_SCRIPTS_CONFIG="${XDG_CONFIG_HOME}/bs-scripts"
+        dbg_print "Using XDG_CONFIG_HOME for configuration"
+    elif [ -f "~/.config/bs-scripts/bs-repo.cfg" ]
+    then
+        # found repo config in ~/.config ...
+        BS_SCRIPTS_CONFIG=$(realpath "~/.config/bs-scripts")
+        dbg_print "Using local config"
+    else
+        # try the scripts dir
+        BS_SCRIPTS_CONFIG="$(realpath ${SCRIPT_DIR})"
+        dbg_print "Using scripts dir"
+    fi
+
+    dbg_print "I think my configuration is here:"
+    dbg_print "[${BS_SCRIPTS_CONFIG}]"
+    REPO_CONFIG_FILE="${BS_SCRIPTS_CONFIG}/bs-repo.cfg"
+    if [ -f "${REPO_CONFIG_FILE}" ]
+    then
+        dbg_print "Using config: ${REPO_CONFIG_FILE}"
+    else
+        echo "I could not find configuration file:"
+        echo "[${REPO_CONFIG_FILE}]"
+        exit 1
+    fi
+}
+
+# list all the available backup configuration
+# configuration is established before this is called
 list()
 {
+    local cwd
+    cwd="$(pwd)"
+    cd "${BS_SCRIPTS_CONFIG}"
     echo ""
     echo "Available backup configurations"
     echo "-------------------------------"
@@ -65,12 +135,10 @@ list()
         printf "%-16s %s\n" "${setname}" "${BACKUP_SET_DESCRIPTION}"
     done
     echo ""
+    cd "${cwd}"
 }
 
 trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
-
-# switch to script directory
-cd "$(dirname "$0")" || { echo "error cd to script directory"; exit 1; }
 
 # initialize prune and compact defaults
 doprune=1
@@ -94,20 +162,22 @@ fi
 # otherwise, process the options
 # this does not do a lot of cross checking of options so it is possible
 # to specify nonsense set of options
-while getopts ":lvhb:t:n:" opt; do
+while getopts ":lvVhb:t:n:" opt; do
     case ${opt} in
         h)
             usage
             exit 0
             ;;
-        v)
+        V)
             echo "bs-backup from bs-scripts package ${VER}"
             echo "https://github.com/kroesche/bs-scripts"
             exit 0
             ;;
+        v)
+            verbose=1
+            ;;
         l)
-            list
-            exit 0
+            action="list"
             ;;
         b)
             if [ "${action}" = "test" ]
@@ -155,6 +225,15 @@ while getopts ":lvhb:t:n:" opt; do
     esac
 done
 
+# remaining commands require access to configuration file
+get_config
+
+if [ "${action}" == "list" ]
+then
+    list
+    exit 0
+fi
+
 # determine command action
 # --stats and --dry-run are not compatible switches for borg
 if [ "${action}" = "backup" ]
@@ -198,18 +277,22 @@ fi
 
 info "using set name: ${setname}, action: ${action}"
 
-# determine configuration file names
+# determine configuration files
 #
-# repo_config contains the definitions of the BORG_REPO env variables.
-# It should define BORG_REPO and BORG_PASSPHRASE or BORG_PASSCOMMAND
-# these should be exports so the file can be sourced
+# REPO_CONFIG_FILE was set by get_config already
 #
-repo_config_file="bs-repo.cfg"        # BORG_REPO, etc
+# BS_SCRIPTS_CONFIG is the path where all the other config files should be
 
 # common exclude is a list of files/folders to exclude using the borg
 # pattern style. one exclusion per line in the file
 #
-common_exclude_file="bs-exclude-common.txt"
+# make sure there is at least a default file present in the config
+COMMON_EXCLUDE_FILE="${BS_SCRIPTS_CONFIG}/bs-exclude-common.cfg"
+if [ ! -f "${COMMON_EXCLUDE_FILE}" ]
+then
+    info "No exclude file found: ${COMMON_EXCLUDE_FILE}"
+    exit 1
+fi
 
 # set_config is the config file for the specific backup set
 # it is of the form:
@@ -228,15 +311,15 @@ common_exclude_file="bs-exclude-common.txt"
 # * BACKUP_SOURCE_PATHS must have at least one path, but can have more than one
 # * the file can have comments on lines by themselves
 #
-set_config_file="bs-set-${setname}.cfg"
+SET_CONFIG_FILE="${BS_SCRIPTS_CONFIG}/bs-set-${setname}.cfg"
 
 # make sure backup set is valid based on existence of a config file
-if [ -f "${set_config_file}" ]
+if [ -f "${SET_CONFIG_FILE}" ]
 then
     # read in (source) the custom backup variables
-    . "./${set_config_file}"
+    . "${SET_CONFIG_FILE}"
 else
-    info "No config file found for backup set: ${set_config_file}"
+    info "No config file found for backup set: ${SET_CONFIG_FILE}"
     exit 1
 fi
 
@@ -261,11 +344,11 @@ else
 fi
 
 # validate and source the repo credentials
-if [ -f "${repo_config_file}" ]
+if [ -f "${REPO_CONFIG_FILE}" ]
 then
-    . "./${repo_config_file}"
+    . "${REPO_CONFIG_FILE}"
 else
-    info "No repo config file found: ${repo_config_file}"
+    info "No repo config file found: ${REPO_CONFIG_FILE}"
     exit 1
 fi
 
@@ -287,11 +370,15 @@ info "BORG_PASS... is not shown for security"
 # my mac
 #
 # assemble all the common and custom command line args into one variable
+ARCHIVE="${BORG_REPO}::{hostname}=${setname}-{now}"
 BORG_CLI_ARGS="create
 --verbose --list --show-rc --compression zstd,9 --exclude-caches --exclude-nodump
-${filter} ${action_switch}
---exclude-from ${common_exclude_file}
-${BACKUP_CUSTOM_FLAGS} ::{hostname}-${setname}-{now} ${BACKUP_SOURCE_PATHS}"
+${filter}
+${action_switch}
+--exclude-from ${COMMON_EXCLUDE_FILE}
+${BACKUP_CUSTOM_FLAGS}
+"${ARCHIVE}"
+${BACKUP_SOURCE_PATHS}"
 
 # show what will be called
 info "BORG_CLI_ARGS:"
@@ -300,6 +387,8 @@ info "${BORG_CLI_ARGS}"
 info "+++BACKUP: ${setname}"
 # use xargs to expand args and pass to borg. this seems to work
 echo "${BORG_CLI_ARGS}" | xargs "${BORG}"
+
+backup_exit=$?
 
 info "---BACKUP"
 
@@ -310,8 +399,6 @@ then
     exit 0
 fi
 
-backup_exit=$?
-
 if [ "${doprune}" = 1 ]
 then
     info "+++PRUNE"
@@ -319,7 +406,8 @@ then
     ${BORG} prune --list --glob-archives "{hostname}-${setname}-*" --show-rc    \
         --keep-daily 7                  \
         --keep-weekly 4                 \
-        --keep-monthly 6
+        --keep-monthly 6                \
+        "${BORG_REPO}"
     prune_exit=$?
     info "---PRUNE"
 else
@@ -331,7 +419,7 @@ if [ "${docompact}" = 1 ]
 then
     info "+++COMPACTING"
 
-    ${BORG} compact
+    ${BORG} compact "${BORG_REPO}"
     compact_exit=$?
     info "---COMPACTING"
 else
